---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uvrfocer/public_html/
    - /bin/cp /repositories/lakbayan-travel-and-tours index.php $DEPLOYPATH
    - /bin/cp /repositories/lakbayan-travel-and-tours/backend/chat/ chatmain.php $DEPLOYPATH
